steps:
  build_and_push:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🚀 Building Docker image..."
      - docker build --no-cache -t hemanthr2002/sample-app:latest .
      - echo "$${DOCKER_PASSWORD}" | docker login -u "$${DOCKER_USERNAME}" --password-stdin
      - docker push hemanthr2002/sample-app:latest

  redeploy:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🔄 Redeploying latest Docker image..."
      - docker pull hemanthr2002/sample-app:latest
      - docker rm -f sample-app || true
      - docker run -d -p 8080:80 --name sample-app hemanthr2002/sample-app:latest
